#pragma once

#define MEDIATOR_PORT_NUM 8000

#define MAX_MSG_SIZE 2048

enum CORE_TOPICS
{
    SUB_REGISTER = 80,
    PUB_REGISTER,
    SUB_NOTIFY,
    PUB_NOTIFY,
    SUB_DEREGISTER,
    PUB_DEREGISTER,
    SUB_DISCONNECT,
    PUB_DISCONNECT,
    SUB_REQUEST,
    PUB_RESPONSE,
    SUB_RESPONSE
};