#pragma once

#define SOCKET_CONNECT_TIMEOUT 5 // seconds

enum SOCKET_STATUS {
    SOCKET_INVALID_URI = -100,
    SOCKET_FD_ERROR,
    SOCKET_FCNTL_ERROR,
    SOCKET_GETSOCKNAME_ERROR,
    SOCKET_NOT_OPENED,
    SOCKET_NOT_CONNECTED,
    SOCKET_NOT_BOUND,
    SOCKET_NOT_LISTENING,
    SOCKET_BIND_FAILED,
    SOCKET_LISTEN_FAILED,
    SOCKET_ACCEPT_FAILED,
    SOCKET_CONNECT_FAILED,
    SOCKET_SEND_FAILED,
    SOCKET_RECV_FAILED,
    SOCKET_ENDPOINT_ERROR,

    SOCKET_OK = 0,
    SOCKET_CLOSED,
    SOCKET_CONNECTED,
    SOCKET_CONNECTING,
    SOCKET_OPENED,
    SOCKET_BOUND,
    SOCKET_LISTENING,
    SOCKET_OP_IN_PROGRESS,
    SOCKET_OP_WOULD_BLOCK,
    SOCKET_MAX_CONNECTIONS,
};

#define SOCKET_STATUS_IS_WARNING(x) (x > 0)
#define SOCKET_STATUS_IS_ERROR(x) (x < 0)
#define SOCKET_STATUS_IS_OK(x) (x == 0)